#!/bin/sh

matchedGroup=$(awk '
BEGIN { flag = 0 }
/^\s*[Hh]ost\s+github\.com/ {
  flag = 1
  print
  next
}
flag && /^\s/ {
  print
  next
}
flag && /^[^\s]/ {
  flag = 0
}
' ~/.ssh/config)

if [ -n "$matchedGroup" ]; then
  file_path=$(echo "$matchedGroup" | grep "IdentityFile")
  # Check if file_path is non-empty and is a string
  if [[ -n "$file_path" ]]; then
    # Extract the email using sed
    email=$(echo "$file_path" | grep -oP '(?<=\.ssh\\)[^\\]+')
    echo -e "\nYou are currently commiting as: $email.\nType 'git reset --soft HEAD~1' to revert.\n"
  else
    echo -e "\nI could not find your email.\nType 'git reset --soft HEAD~1' to revert.\n"
  fi
else
  echo -e "\nI could not find your ssh config.\nType 'git reset --soft HEAD~1' to revert.\n"
fi